### ISSUE TITLE
Running on Colab - Lib version mismatch with current req.txt file, + Unable to access data that is present

### ISSUE THREAD

**Issue by pandaaditi91-1** [xmindflow/WaveFormer#2]
scipy onwards there is version mismatch - they need python <3.10, but installing a different version in colab isn't working

**Comment by pandaaditi91-1** [comment]
AttributeError: 'Delaunay' object has no attribute 'vertices'

This is the exact error

**Comment by pandaaditi91-1** [comment]
I removed all version numbers from requirements.txt and the errors are gone!

But now, all the files have been successfully downloaded(Synapse Dataset) but the code is not able to access them. I keep getting a **case0031_slice000.npz File Not Found** Error.

**Comment by amirhossein-kz** [comment]
Hi @pandaaditi91-1 
Thank you for notifying us. I will update the `requirements.txt file`.
Make sure you add the correct path to `root_path` and `test_path`.
